#macro DRAW_OFFSET 8
#macro MAX_HEIGHT 4
#macro GRID_SCALE 8
#macro MOVE_COST 1
#macro DIAGONAL_COST 1.42
#macro LONG_COST 2
#macro FAR_COST 2.3
#macro HEIGHT_COST 1
#macro HEURISTIC_POWER 1.2
#macro HEIGHT_POWER 1.1
#macro ITERATION_LIMIT 20000

#macro GUI_DEPTH -10000
#macro PARTICLE_DEPTH -500

#macro MOB_LAND 0
#macro MOB_WATER 1
#macro MOB_GEV 2
#macro MOB_AIR 3

#macro EQUALS 187
#macro SUBTRACT 189